[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts"
edition = "2024"
publish = false

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/vortex-data/vortex.git", rev = "f9093dffd2cd0212d90a65198815ecd2ea385762" }

# Geospatial patch as we have multiple dependency versions in our tree
[patch.crates-io]
geoarrow = { version = "=0.8.0", git = "https://github.com/geoarrow/geoarrow-rs", rev = "855d2e138e54ce503c4488d5bb795ca1ea880d1f" }
geoarrow-array = { version = "=0.8.0", git = "https://github.com/geoarrow/geoarrow-rs", rev = "855d2e138e54ce503c4488d5bb795ca1ea880d1f" }
geoarrow-cast = { version = "=0.8.0", git = "https://github.com/geoarrow/geoarrow-rs", rev = "855d2e138e54ce503c4488d5bb795ca1ea880d1f" }
geoarrow-schema = { version = "=0.8.0", git = "https://github.com/geoarrow/geoarrow-rs", rev = "855d2e138e54ce503c4488d5bb795ca1ea880d1f" }

# This improved build times significantly
[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
